# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wop < Formula
  desc "CLI to spin up isolated per-branch dev environments with git worktrees"
  homepage "https://github.com/sofiandreoli/wop-releases"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sofiandreoli/wop-releases/releases/download/v1.0.0/wop_1.0.0_darwin_amd64.tar.gz"
      sha256 "352164f44cba520807cc6faf5acb01bc7a3a5faba8bc4b68ec9e34313abd78d5"

      define_method(:install) do
        bin.install "wop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sofiandreoli/wop-releases/releases/download/v1.0.0/wop_1.0.0_darwin_arm64.tar.gz"
      sha256 "61bbfb50794c599d34822ac1f670040241cc4c8963ea585952fc878d1e28de82"

      define_method(:install) do
        bin.install "wop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/wop-releases/releases/download/v1.0.0/wop_1.0.0_linux_amd64.tar.gz"
      sha256 "6e1c35628a24da7361cf7a54b6996cc2f60cf6b5a524af9fd32934c135efc0c2"
      define_method(:install) do
        bin.install "wop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/wop-releases/releases/download/v1.0.0/wop_1.0.0_linux_arm64.tar.gz"
      sha256 "7177b7cf9b0a747e4aec5e8fe88751e11aa9ffefe8f1fbfedcd05d6e68b2fe84"
      define_method(:install) do
        bin.install "wop"
      end
    end
  end

  test do
    system "#{bin}/wop", "--version"
  end
end
