# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wop < Formula
  desc "CLI to spin up isolated per-branch dev environments with git worktrees"
  homepage "https://github.com/sofiandreoli/wop-releases"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sofiandreoli/wop-releases/releases/download/v0.1.7/wop_0.1.7_darwin_amd64.tar.gz"
      sha256 "57a762b0b434c7017bffdad7863e84c3e4f256553dfcef2e45e0a67eb356070f"

      define_method(:install) do
        bin.install "wop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sofiandreoli/wop-releases/releases/download/v0.1.7/wop_0.1.7_darwin_arm64.tar.gz"
      sha256 "36a5e5ac24f9904d0e1366115979b958272265e8262d5580968370c53f288ec8"

      define_method(:install) do
        bin.install "wop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/wop-releases/releases/download/v0.1.7/wop_0.1.7_linux_amd64.tar.gz"
      sha256 "c01b694430c6dd5b2deb0f142184c2bf8add561a787edf454148669dbd15635c"
      define_method(:install) do
        bin.install "wop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/wop-releases/releases/download/v0.1.7/wop_0.1.7_linux_arm64.tar.gz"
      sha256 "3538158aa66bf77d2e496e7c0464abb1b7ef6e626328a8c6fce6fb57521eb0ef"
      define_method(:install) do
        bin.install "wop"
      end
    end
  end

  test do
    system "#{bin}/wop", "--version"
  end
end
